behaviors:
  LeadVehicle:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2024
      buffer_size: 20240
      learning_rate: 0.0003
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      hidden_units: 512
      num_layers: 3
      normalize: false
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
      gail:
        strength: 1
        gamma: 0.99
        network_settings:
          normalize: true
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
        learning_rate: 0.0003
        demo_path: config/imitation/LeadTruck.demo
    behavioral_cloning:
      strength: 1
      steps: 50000
      demo_path: config/imitation/LeadTruck.demo
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 10000
    threaded: false